apiVersion: apps/v1
kind: Deployment
metadata:
  name: rti-app
  namespace: rti
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rti-app
  template:
    metadata:
      labels:
        app: rti-app
    spec:
      containers:
      - name: rti-app
        image: mmregistry.mmvietnam.com:5000/rti:v4
        ports:
        - containerPort: 7003
        env:
        - name: NODE_ENV
          value: "UAT"
        - name: SERVICE
          value: "consumer"
      imagePullSecrets:
      - name: mmregistry-secret
