apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-app
  namespace: customer2es
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer-app
  template:
    metadata:
      labels:
        app: consumer-app
    spec:
      containers:
      - name: consumer-container
        image: mmregistry.mmvietnam.com:5000/customer2es:latest
        ports:
        - containerPort: 7001  # Consumer service port
        - containerPort: 7002  # Producer service port
        env:
        - name: NODE_ENV
          value: "UAT"
        - name: CONSUMER_SERVICE
          valueFrom:
            configMapKeyRef:
              name: service-config
              key: CONSUMER_SERVICE
        - name: PRODUCER_SERVICE
          valueFrom:
            configMapKeyRef:
              name: service-config
              key: PRODUCER_SERVICE
      imagePullSecrets:
      - name: mmregistry-secret
