apiVersion: v1
kind: Service
metadata:
  name: consumer-service
  namespace: customer2es
spec:
  selector:
    app: consumer-app
  ports:
    - name: consumer-port
      protocol: TCP
      port: 7001        # Exposed port
      targetPort: 7001
    - name: producer-port
      protocol: TCP
      port: 7002        # Exposed port
      targetPort: 7002
  type: LoadBalancer
