apiVersion: v1
kind: Service
metadata:
  name: rti-service
  namespace: rti  # namespace the same deployement
spec:
  selector:
    app: rti-app  #  Pod choose Deployment label
  ports:
    - protocol: TCP
      port: 7003           # Port extenal
      targetPort: 7003    # Port in container
  type: LoadBalancer     # LoadBalancer provide IP address
