apiVersion: v1
kind: Service
metadata:
  name: customer2es-service
  namespace: customer2es  # namespace the same deployement
spec:
  selector:
    app: customer2es-app  #  Pod choose Deployment label
  ports:
    - protocol: TCP
      port: 7002           # Port extenal
      targetPort: 7002       # Port in container
      #- protocol: TCP
      #port: 7002           # Port extenal
      #targetPort: 7002       # Port in container
  type: LoadBalancer     # LoadBalancer provide IP address
